CREATE TABLE IF NOT EXISTS materi (
    id INT(11) AUTO_INCREMENT PRIMARY KEY,
    kelas_id INT(11) NOT NULL,
    judul VARCHAR(255) NOT NULL,
    deskripsi TEXT,
    konten TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (kelas_id) REFERENCES kelas_programming(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
