#!/usr/bin/env php
<?php

/**
 * Simple server starter for CodeIgniter 3
 */

if (str_starts_with(PHP_SAPI, 'cgi')) {
    exit("The cli tool is not supported when running php-cgi. It needs php-cli to function!\n\n");
}

$minPhpVersion = '5.3.7';
if (version_compare(PHP_VERSION, $minPhpVersion, '<')) {
    $message = sprintf(
        'Your PHP version must be %s or higher to run CodeIgniter. Current version: %s',
        $minPhpVersion,
        PHP_VERSION,
    );
    exit($message);
}

error_reporting(E_ALL);
ini_set('display_errors', '1');

// Check if 'serve' command is used
$args = $argv;
if (isset($args[1]) && $args[1] === 'serve') {
    $host = isset($args[2]) ? $args[2] : 'localhost:8000';
    echo "Starting server on http://$host\n";
    echo "Press Ctrl+C to stop\n";
    passthru("php -S $host index.php");
} else {
    echo "Usage: php spark serve [host:port]\n";
    echo "Example: php spark serve localhost:8000\n";
}
