<div class="space-y-4">
    <!-- Header with Calendar -->
    <div class="mobile-card">
        <div class="flex items-center justify-between mb-4">
            <h2 class="text-xl font-bold text-gray-900">Absensi Saya</h2>
            <button onclick="location.href='<?= site_url("student_mobile") ?>'" class="p-2 rounded-lg hover:bg-gray-100 transition-colors">
                <i data-feather="arrow-left" class="w-5 h-5 text-gray-600"></i>
            </button>
        </div>
        
        <!-- Month Navigation -->
        <div class="flex items-center justify-between mb-4">
            <button onclick="changeMonth(-1)" class="p-2 rounded-lg hover:bg-gray-100 transition-colors">
                <i data-feather="chevron-left" class="w-5 h-5 text-gray-600"></i>
            </button>
            <h3 class="text-lg font-semibold text-gray-900" id="currentMonth"><?php echo date('F Y'); ?></h3>
            <button onclick="changeMonth(1)" class="p-2 rounded-lg hover:bg-gray-100 transition-colors">
                <i data-feather="chevron-right" class="w-5 h-5 text-gray-600"></i>
            </button>
        </div>
        
        <!-- Calendar Grid -->
        <div class="grid grid-cols-7 gap-1 text-center text-xs">
            <div class="text-gray-500 font-medium py-2">Min</div>
            <div class="text-gray-500 font-medium py-2">Sen</div>
            <div class="text-gray-500 font-medium py-2">Sel</div>
            <div class="text-gray-500 font-medium py-2">Rab</div>
            <div class="text-gray-500 font-medium py-2">Kam</div>
            <div class="text-gray-500 font-medium py-2">Jum</div>
            <div class="text-gray-500 font-medium py-2">Sab</div>
            
            <!-- Calendar days will be generated by JavaScript -->
            <div id="calendarDays" class="col-span-7 grid grid-cols-7 gap-1">
                <!-- Calendar days will be inserted here -->
            </div>
        </div>
    </div>

    <!-- Attendance Summary -->
    <div class="mobile-card">
        <h3 class="text-lg font-bold text-gray-900 mb-4">Ringkasan Absensi</h3>
        <div class="grid grid-cols-2 gap-3">
            <div class="bg-green-50 rounded-lg p-3 text-center">
                <div class="text-2xl font-bold text-green-600"><?php echo $attendance_summary['hadir'] ?? 0; ?></div>
                <div class="text-xs text-gray-600">Hadir</div>
            </div>
            <div class="bg-red-50 rounded-lg p-3 text-center">
                <div class="text-2xl font-bold text-red-600"><?php echo $attendance_summary['tidak_hadir'] ?? 0; ?></div>
                <div class="text-xs text-gray-600">Tidak Hadir</div>
            </div>
            <div class="bg-yellow-50 rounded-lg p-3 text-center">
                <div class="text-2xl font-bold text-yellow-600"><?php echo $attendance_summary['izin'] ?? 0; ?></div>
                <div class="text-xs text-gray-600">Izin</div>
            </div>
            <div class="bg-blue-50 rounded-lg p-3 text-center">
                <div class="text-2xl font-bold text-blue-600"><?php echo $attendance_summary['sakit'] ?? 0; ?></div>
                <div class="text-xs text-gray-600">Sakit</div>
            </div>
        </div>
        
        <!-- Attendance Rate -->
        <div class="mt-4">
            <div class="flex items-center justify-between mb-2">
                <span class="text-sm text-gray-600">Tingkat Kehadiran</span>
                <span class="text-sm font-medium text-gray-900"><?php echo $attendance_rate ?? '0%'; ?></span>
            </div>
            <div class="w-full bg-gray-200 rounded-full h-2">
                <div class="bg-green-600 h-2 rounded-full" style="width: <?php echo $attendance_rate ?? '0%'; ?>"></div>
            </div>
        </div>
    </div>

    <!-- Recent Attendance Records -->
    <div class="mobile-card">
        <div class="flex items-center justify-between mb-4">
            <h3 class="text-lg font-bold text-gray-900">Rekaman Absensi Terbaru</h3>
            <button class="text-blue-600 text-sm font-medium">Lihat Semua</button>
        </div>
        
        <?php if (empty($attendance_records)): ?>
            <div class="text-center py-8">
                <i data-feather="calendar" class="w-16 h-16 text-gray-300 mx-auto mb-4"></i>
                <h4 class="text-lg font-medium text-gray-900 mb-2">Belum ada data absensi</h4>
                <p class="text-sm text-gray-500">Data absensi akan muncul setelah Anda mengikuti kelas</p>
            </div>
        <?php else: ?>
            <div class="space-y-3">
                <?php foreach($attendance_records as $record): ?>
                    <div class="border border-gray-200 rounded-lg p-4">
                        <div class="flex items-start justify-between mb-2">
                            <div>
                                <h4 class="text-sm font-medium text-gray-900"><?php echo $record['judul_pertemuan']; ?></h4>
                                <p class="text-xs text-gray-500"><?php echo $record['nama_kelas']; ?></p>
                            </div>
                            <span class="px-2 py-1 text-xs font-medium rounded-full <?php echo $this->Absensi_model->get_status_class($record['status']); ?>">
                                <?php echo $record['status']; ?>
                            </span>
                        </div>
                        <div class="flex items-center justify-between text-xs text-gray-500">
                            <span><i data-feather="calendar" class="w-3 h-3 inline mr-1"></i><?php echo date('d M Y', strtotime($record['tanggal_pertemuan'])); ?></span>
                            <span><i data-feather="clock" class="w-3 h-3 inline mr-1"></i><?php echo date('H:i', strtotime($record['waktu_mulai'])); ?></span>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>
    </div>

</div>

<script>
    let currentDate = new Date();
    
    function generateCalendar(year, month) {
        const firstDay = new Date(year, month, 1).getDay();
        const daysInMonth = new Date(year, month + 1, 0).getDate();
        const today = new Date();
        
        let calendarHTML = '';
        
        // Empty cells for days before month starts
        for (let i = 0; i < firstDay; i++) {
            calendarHTML += '<div></div>';
        }
        
        // Days of the month
        for (let day = 1; day <= daysInMonth; day++) {
            const isToday = today.getFullYear() === year && today.getMonth() === month && today.getDate() === day;
            const hasAttendance = <?php echo json_encode($attendance_dates); ?>[`${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`];
            
            let statusClass = 'bg-gray-100 text-gray-600';
            if (isToday) statusClass = 'bg-blue-600 text-white';
            else if (hasAttendance) {
                statusClass = 'bg-green-100 text-green-800';
            }
            
            calendarHTML += `<div class="p-2 rounded-lg text-center cursor-pointer hover:bg-gray-100 transition-colors ${statusClass}">
                <span class="text-sm">${day}</span>
            </div>`;
        }
        
        document.getElementById('calendarDays').innerHTML = calendarHTML;
    }
    
    function changeMonth(direction) {
        currentDate.setMonth(currentDate.getMonth() + direction);
        updateCalendarDisplay();
    }
    
    function updateCalendarDisplay() {
        const monthNames = ['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 
                           'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember'];
        
        document.getElementById('currentMonth').textContent = 
            monthNames[currentDate.getMonth()] + ' ' + currentDate.getFullYear();
        
        generateCalendar(currentDate.getFullYear(), currentDate.getMonth());
    }
    
    // Initialize calendar
    document.addEventListener('DOMContentLoaded', function() {
        feather.replace();
        updateCalendarDisplay();
    });
</script>